#!/usr/bin/env python3
from __future__ import unicode_literals, print_function

import json
import subprocess

info_json = subprocess.check_output(
    ['brew', 'info', '--installed', '--json=v1']).decode()
formulae = json.loads(info_json)

head_formulae = (
    f for f in formulae
    if any(ins['version'] == 'HEAD' for ins in f['installed']))

for f in head_formulae:
    name = f['name']
    print('Reinstalling', name)
    if f.get('linked_keg'):
        current_version = next(v for v in f['installed'] if v['version'] == f['linked_keg'])
    else:
        current_version = f['installed'][0]
    opts = current_version.get('used_options') or []
    args = ['brew', 'reinstall', '--verbose', '--HEAD', name] + opts
    subprocess.check_call(args)
