#!/bin/sh

# Upgrade all HEAD formula by calling `brew reinstall --HEAD $FORMULAE`

die () {
    echo "$1"
    exit 1
}

which jq || die "jq not installed"

HEADS_INFO=$(brew info --installed --json=v1 | jq -r 'map(select(.installed | map(.version) | contains(["HEAD"])))')

echo "HEAD formulae:" $(echo "$HEADS_INFO" | jq -r '.[].name')

FORMULAE_AND_ARGS=$(echo $HEADS_INFO | jq -r '.[] | .name as $name | (.installed[] | select(.version == "HEAD")) | .used_options | $name + " " + join(" ")')

IFS=$'\n'
for args in $FORMULAE_AND_ARGS; do
    set -x
    eval "brew reinstall -v --HEAD $args"
done
